# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test suite

on: [push, pull_request]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        meteor-release: 
          - '--release 2.8.2'
          - '--release 3.1'
    # needs: [lintcode,lintstyle,lintdocs] # we could add prior jobs for linting, if desired
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          curl https://install.meteor.com | /bin/sh
          npm i -g @zodern/mtest

      - name: Run Tests
        run: |
          # Fix using old versions of Meteor
          export NODE_TLS_REJECT_UNAUTHORIZED=0

          mtest --package ./ --once ${{ matrix.meteorRelease }}
